server:
  port: 9000

springdoc:
  api-docs:
    path: /teamvc-api-docs
  swagger-ui:
    path: /teamvc-api-docs-ui.html

# H2 DATABASE
# spring:
#   datasource:
#     url: jdbc:h2:mem:mydb
#     username: sa
#     password: password
#     driverClassName: org.h2.Driver
#   jpa:
#     database-platform: org.hibernate.dialect.H2Dialect

spring:
  datasource:
    # url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/teamvc?createDatabaseIfNotExist=true&useSSL=true
    url: jdbc:mysql://mysql-server-2.mysql.database.azure.com:3306/teamvc?createDatabaseIfNotExist=true&useSSL=true
    username: hbcordova
    password: Lck4Cg*M!&9qjjQ
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
        ddl-auto: update
